# Generated by Django 3.0.4 on 2020-03-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidade',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, unique=True)),
        ),
    ]
