# Generated by Django 3.0.4 on 2020-03-27 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-dia']},
        ),
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('medico', 'dia')},
        ),
    ]
