# Generated by Django 3.0.4 on 2020-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20200327_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='slug',
        ),
    ]
