# Generated by Django 3.0.4 on 2020-03-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulta',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='consulta',
            unique_together=set(),
        ),
    ]
