ESPECIALIDADE_CHOICES = (
    ('IMUNOLOGIA', 'Imunologia'),
    ('ANGIOLOGIA', 'Angiologia'),
    ('ONCOLOGIA', 'Oncologia'),
    ('CARDIOLOGIA', 'Cardiologia'),
    ('CLINICA_GERAL', 'Clinica Geral'),
    ('CIRURGIA', 'Cirurgia'),
    ('COLOPROCTOLOGIA', 'Coloproctologia'),
    ('DERMATOLOGIA', 'Dermatologia'),
    ('ENDOCRINOLOGIA', 'Endocrinologia'),
    ('GASTROENTEROLOGIA', 'Gastroenterologia'),
    ('GERIATRIA', 'Geriatria'),
    ('GINECOLOGIA', 'Ginecologia'),
    ('HEMATOLOGIA', 'Hematologia'),
    ('INFECTOLOGIA', 'Infectologia'),
    ('MASTOLOGIA', 'Mastologia'),
    ('NEFROLOGIA', 'Nefrologia'),
    ('NEUROLOGIA', 'Neurologia'),
    ('NUTROLOGIA', 'Nutrologia'),
    ('OBSTETRICIA', 'Obstetricia'),
    ('OFTALMOLOGIA', 'Oftalmologia'),
    ('ORTOPEDIA', 'Ortopedia'),
    ('OTORRINOLARINGOLOGIA', 'Otorrinolaringologia'),
    ('PEDIATRIA', 'Pediatria'),
    ('PNEUMOLOGIA', 'Pneumologia'),
    ('PSIQUIATRIA', 'Psiquiatria'),
    ('RADIOLOGIA', 'Radiologia'),
    ('RADIOTERAPIA', 'Radioterapia'),
    ('REUMATOLOGIA', 'Reumatologia'),
    ('UROLOGIA', 'Urologia'),
)