# Generated by Django 3.0.4 on 2020-03-27 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(default=datetime.date.today)),
                ('horarios', models.CharField(choices=[('8', '8:00 - 9:00'), ('9', '9:00 - 10:00'), ('10', '10:00 - 11:00'), ('11', '11:00 - 12:00'), ('12', '12:00 - 13:00'), ('13', '13:00 - 14:00'), ('14', '14:00 - 15:00'), ('15', '15:00 - 16:00'), ('16', '16:00 - 17:00'), ('17', '17:00 - 18:00'), ('18', '18:00 - 19:00'), ('19', '19:00 - 20:00'), ('20', '20:00 - 21:00')], default='8', max_length=12)),
                ('slug', models.SlugField(default='<built-in function id>')),
                ('medico', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='medicos.Medico')),
            ],
        ),
    ]
