# Generated by Django 2.2.6 on 2020-03-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=200, null=True, unique=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('especialidade', models.CharField(choices=[('IMUNOLOGIA', 'Imunologia'), ('ANGIOLOGIA', 'Angiologia'), ('ONCOLOGIA', 'Oncologia'), ('CARDIOLOGIA', 'Cardiologia'), ('CLINICA_GERAL', 'Clinica Geral'), ('CIRURGIA', 'Cirurgia'), ('COLOPROCTOLOGIA', 'Coloproctologia'), ('DERMATOLOGIA', 'Dermatologia'), ('ENDOCRINOLOGIA', 'Endocrinologia'), ('GASTROENTEROLOGIA', 'Gastroenterologia'), ('GERIATRIA', 'Geriatria'), ('GINECOLOGIA', 'Ginecologia'), ('HEMATOLOGIA', 'Hematologia'), ('INFECTOLOGIA', 'Infectologia'), ('MASTOLOGIA', 'Mastologia'), ('NEFROLOGIA', 'Nefrologia'), ('NEUROLOGIA', 'Neurologia'), ('NUTROLOGIA', 'Nutrologia'), ('OBSTETRICIA', 'Obstetricia'), ('OFTALMOLOGIA', 'Oftalmologia'), ('ORTOPEDIA', 'Ortopedia'), ('OTORRINOLARINGOLOGIA', 'Otorrinolaringologia'), ('PEDIATRIA', 'Pediatria'), ('PNEUMOLOGIA', 'Pneumologia'), ('PSIQUIATRIA', 'Psiquiatria'), ('RADIOLOGIA', 'Radiologia'), ('RADIOTERAPIA', 'Radioterapia'), ('REUMATOLOGIA', 'Reumatologia'), ('UROLOGIA', 'Urologia')], default='CLINICA GERAL', max_length=20, null=True)),
            ],
        ),
    ]
