# Generated by Django 3.0.4 on 2020-03-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('crm', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('especialidade', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidades.Especialidade')),
            ],
        ),
    ]
